# This is a basic workflow to help you deploy an ADF ARM template to a higher environment

# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - adf_publish
permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  build:
    environment:
      name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
 
    name: 'This deploys to Production'
    steps:
    - uses: actions/checkout@v3
      with:
          ref: adf_publish

    
    - name: Azure Login
      uses: Azure/login@v2.1.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
    - name: Print Parameters
      env:
        parameter: "Integrated Security=False;Data Source=10.56.3.24;Initial Catalog=test;User ID=admini"
      run: echo "SqlServer1_connectionString=${{ env.parameter }} AzureKeyVault1_properties_typeProperties_baseUrl=https://sqlservercred.vault.azure.net/"

        
    # - name: Azure PowerShell Action
    #   uses: Azure/powershell@v1
    #   with:
    #     # Specify the Az PowerShell script here.
    #     inlineScript: ./devl-demo-adf/PrePostDeploymentScript.Ver2.ps1 -armTemplate "./devl-demo-adf/ARMTemplateForFactory.json" -ResourceGroupName vinayak-rg -DataFactoryName prod-demo-adf -predeployment $true -deleteDeployment $false
          
    #   # Azure PS version to be used to execute the script, example: 1.8.0, 2.8.0, 3.4.0. To use the latest version, specify "latest".
    #     azPSVersion: latest

    - name: data-factory-deploy
      uses: Azure/data-factory-deploy-action@v1.2.0
      env:
                ARM_USE_AZUREREAD: true
                ARM_USE_OIDC: true
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                parameter: Integrated Security=False;Data Source=10.56.3.24;Initial Catalog=test;User ID=admini
      with:
        # Data Factory resource group name
        resourceGroupName: Shoaib_RG
        # Data factory name
        dataFactoryName: adfTarget01
        armTemplateFile: ./adfSource01/ARMTemplateForFactory.json
        # ARM template parameters file name
        armTemplateParametersFile: ./adfSource01/ARMTemplateParametersForFactory.json
        # Parameters which will be replaced in the ARM template
        additionalParameters: factoryName=adfTarget01 SqlServer1_connectionString=${{ env.parameter }} AzureKeyVault1_properties_typeProperties_baseUrl=https://sqlservercred.vault.azure.net/

      

    
    # - name: Deploy Azure Resource Manager (ARM) Template
    #   uses: Azure/arm-deploy@v1.0.6
    #   env:
    #             ARM_USE_AZUREREAD: true
    #             ARM_USE_OIDC: true
    #             client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #             tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #             subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #             parameter: Integrated Security=False;Data Source=10.56.3.24;Initial Catalog=test;User ID=admini
    #   with:
    #     # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
    #     scope: 'resourcegroup'
    #     # Target resource group of the deployment.
    #     resourceGroupName: 'Shoaib_RG'
    #     # Specify the path to the ADF ARM template. In this scenario, the workflow is in the same branch, 
    #     # hence we only add the folder and arm template name to the path
    #     template: ./adfSource01/ARMTemplateForFactory.json
    #     # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group) or Validate (only validates the template).
    #     deploymentMode: Incremental
    #     # Supply deployment parameter values. In this simple scenario, 
    #     # I am only passing the name of the target ADF to which this is being deployed
    #     parameters: adfSource01/ARMTemplateParametersForFactory.json factoryName=adfTarget01 SqlServer1_connectionString=${{ env.parameter }} AzureKeyVault1_properties_typeProperties_baseUrl=https://sqlservercred.vault.azure.net/
